services:
  backend:
    image: polygame-api-prod
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      APP_PORT: 80
      DATABASE_URL: "${DATABASE_URL}"
      FRONTEND_URL: "${FRONTEND_URL}"
      JWT_ACCESS_SECRET: "${JWT_ACCESS_SECRET}"
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"
      COOKIE_DOMAIN: "${COOKIE_DOMAIN}"
    ports:
      - "${HOST_BACKEND_PORT}:80"
    networks:
      - backend-network
    depends_on:
      - db
  frontend:
    image: polygame-front-prod
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        NUXT_PUBLIC_API_BASE: "${BACKEND_API_BASE}"
    ports:
      - "${HOST_FRONTEND_PORT}:80"
  db:
    volumes:
      - db-prod-data:/var/lib/postgresql/data

networks:
  backend-network:

volumes:
  db-prod-data:
    driver: local
